apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ps-only
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ps-only
    spec:
      containers:
        - name: process-services
          env:
            - name: ACTIVITI_CORS_ENABLED
              value: 'true'
            - name: ACTIVITI_CSRF_DISABLED
              value: 'true'
          image: alfresco/process-services:1.6.1
          ports:
            - containerPort: 8080
